# 服务器配置
server:
  port: 8000
  mode: debug

# PostgresSQL 数据库配置
database:
  host: 10.1.1.136
  port: 5432
  user: postgres
  password: gsm200818534
  dbname: go
  sslmode: disable

# Redis 配置
redis:
  host: 10.1.1.136
  port: 6379
  password: gsm200818534
  db: 0
  pool_size: 8
  min_idle_conns: 2

# RabbitMQ 配置
rabbitmq:
  host: 60.205.140.163
  port: 5672
  user: rabbitmq
  password: rabbitmq
  vhost: /
  exchange: sensor_data
  queue: sensor_data_queue
  routing_key: sensor_data_key

# MQTT 配置
mqtt:
  broker: tcp://60.205.140.163:1883
  client_id: go_mqtt_client
  username: "admin"
  password: "password"

# JWT 配置
jwt:
  secret: K9f4zB2qX8vL7nA1pR6sT5wM3cN9xY2hV7jQ4mE6oI5uP8tW1rS3eD7yH6kL9vC4n
  expire: 24 # 小时

# CORS 配置
cors:
  allow_origins:
    - http://localhost:5173
    - http://localhost:8080
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Authorization
  expose_headers:
    - Content-Length
  allow_credentials: true
  max_age: 43200 # 12小时

# Elasticsearch 配置
elasticsearch:
  enabled: true
  host: 43.136.37.113
  port: 9200
  username: elastic
  password: F*EtjS0XwPcaHjR4SwgB
  index: sensor-log
  sniff: false
